# Site settings
title:          Interactive Mechanics
email:          hello@interactivemechanics.com
description:    Interactive user experience design & development building beautiful digital projects
thumb:          "/images/uploads/focus-web.jpg"


# Collections
collections:
  work:
    output:     true
    permalink:  /work/:path/
  workshops:
    output:     true
    permalink:  /workshops/:path/

# Build settings
#url:           "http://localhost:4000"
url:            "http://interactivemechanics.com"
permalink:      /news/:year/:month/:title/
paginate_path:  /page:num
markdown:       kramdown
highlighter:    Pygments